kind: Service 
apiVersion: v1 
metadata: 
  name: flask-service
  namespace: todo-app 
spec: 
  selector:
    app: flask 
    env: dev 
    version: v1 
  type: NodePort 
  ports: 
   - port: 5000
     targetPort: 5000
     nodePort: 30007
     protocol: TCP 
     name: flas-port
